spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
          hibernate:
            format_sql: true
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    # excluded-view-names:
    # mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    # template-resolver-order:
    # view-names:

  datasource:
    url: jdbc:mysql://localhost:3306/ucamu
    username: kbsure
    password: kbsure


image:
  path: ~/image

#logging:
#  file: ~/logs/log.log