spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

  datasource:
    url: jdbc:h2:mem:ucamu;DB_CLOSE_DELAY=-1
    username: kbsure
    password: kbsure
    initialization-mode: always
  h2:
    console:
      enabled: true
#  security:
#    basic:
#      enabled: true
#      authorize-mode: NONE

image:
  path: C:/Users/story/Pictures/ucamu/image